version: '3.9'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=wildlens_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=junior

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=wildlens_database
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=junior
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

volumes:
  postgres_data:
